### ISSUE TITLE
阅读页面的思路能不能出个文档 特别是仿真翻页

### ISSUE THREAD

**Issue by 1641146911** [lwlizhe/flutter_novel#12]
阅读页面的思路能不能出个文档 特别是仿真翻页

**Comment by lwlizhe** [comment]
思路的话，那就看下这个系列喽

[Android自定义View——从零开始实现书籍翻页效果（一）](https://juejin.cn/post/6844903529715335182)

**Comment by lwlizhe** [comment]
另外补充下，
其实像翻起页那种，有些地方反而复杂化了，
另外虽然裁剪会防止过度绘制……但是裁剪很耗性能，如果全是裁剪的话，最终还真不一定比单纯的叠加图层不考虑过度绘制性能好；

不过如果只是思路的话，这篇文章绝对够了

**Comment by 1641146911** [comment]
好的  我去看看

**Comment by 1641146911** [comment]
大佬 如果有空的话 还是出个 阅读页面的文档吧  Android 好多人不会（包括我） 哈哈    目前小说翻页好多人都没有思路 我只是建议哈  /笑哭  /笑哭

**Comment by lwlizhe** [comment]
> 大佬 如果有空的话 还是出个 阅读页面的文档吧 Android 好多人不会（包括我） 哈哈 目前小说翻页好多人都没有思路 我只是建议哈 /笑哭 /笑哭

其实我现在这个flutter 项目思路参考的就是这个，说白了就是用dart翻译一遍，然后稍微改改

Android这块倒是有比较大的改动（其实就是用别的方式缩减那篇文章所述的步骤和实现方式），不过基本思路还是上面那个文章，所以只要看懂上面那个文章，问题就不大，我这也没啥好补充的~~~~~~~~~

总之放心看就是了，当初我也是一脸懵逼，后来跟着写一遍就全明白了
