### ISSUE TITLE
画布问题

### ISSUE THREAD

**Issue by 1641146911** [lwlizhe/flutter_novel#13]
您是画了多个画布 重叠在一起 还是只画两个画布重叠在一起进行操作的  我看到代码中只用到了一个CustomPaint   实在CustomPaint里面有多个画布canvas吗   我比较菜 刚入行 向您请教一下

**Comment by lwlizhe** [comment]
时间有点久，不过记得总体流程是这样的，感觉你需要先了解下这块的基本流程：

1、异步分页计算处理
2、根据分页计算处理的结果，开个isolate，将分页计算的内容绘制，并保存为一个bitmap，当作缓存处理
3、当预加载部分的那一部分缓存完成之后，就开始绘制，也就是再canvas上将页码对应的bitmap绘制上去而已

根据上面的总体流程，canvas从始至终也就一个（其实对于其他任何一个应用来说，canvas也就一个，而且必须是flutter这种平台底层提供的canvas；多个canvas并没有意义甚至是不合法的，canvas本身也不存在合并这种操作），整个过程无非就是对bitmap、layer这些东西的分割、叠加、处理操作；
