### ISSUE TITLE
你这个说法实现了吗 在哪里可以看看

### ISSUE THREAD

**Issue by leetomlee123** [lwlizhe/flutter_novel#15]
![image](https://user-images.githubusercontent.com/19498940/120150565-cb903d80-c21d-11eb-826e-8ab7da679bde.png)

**Comment by lwlizhe** [comment]
额，这个可以参考这个项目，flutter_isolate

**Comment by leetomlee123** [comment]
> 额，这个可以参考这个项目,[flutter_isolate](https://github.com/rmawatson/flutter_isolate)

painter.layout 不是只可以跑在main isolate吗

**Comment by lwlizhe** [comment]
> > 额，这个可以参考这个项目,[flutter_isolate](https://github.com/rmawatson/flutter_isolate)
> 
> painter.layout 不是只可以跑在main isolate吗

没错，但是呢，flutter不一定只能有一个enginer……所以也不一定只有一个main isolate

简单的来说，做法就是，新建一个enginer，不过不绑定native的view，只利用新建的enginer中的isolate；

**Comment by leetomlee123** [comment]
tks
