### ISSUE TITLE
关于快速滑动的问题

### ISSUE THREAD

**Issue by flymzero** [lwlizhe/flutter_novel#18]
大大，想请教一下，无论翻页效果是仿真、覆盖、或者上下滑动，手指快速滑动的话，页面不跟手，是源码二次修改的原因吗？

**Comment by lwlizhe** [comment]
额，是，因为我就这么规定的……在动画结束前不响应任何手势操作……看像小米阅读那个也是这样……

不过Flutter的动画结束判断目测比原生上慢个0.3秒左右，而且确实我为了方便开发，动画设置的相对较慢，所以现在这个问题确实比较明显；

临时性质的方案：

https://github.com/fluttercandies/extended_image/issues/152#issue-579677792

当然，个人感觉，接着重写，把Android 的那套搬过来才是正途～

**Comment by flymzero** [comment]
谢谢解答，我本来想用官方的listview，发现要不就是嵌套手势有问题，要不就是章节处理没法处理😭， 大概学习了一下你的源码（看不太懂😁，自定义SliverList,然后嵌套）这样针对章节的小说，处理起来方便很多。但动画效果这块不知道在自定义SliverList的情况下，能不能和官方的listview达到一样的效果

**Comment by lwlizhe** [comment]
额，官方的ListView，在动画这块其实跟我这个一样的，唯一的不同是官方的ListView允许在动画结束前进行操作打断动画；

而我现在这个不跟手问题之所以体现的这么明显，原因就是这个Flutter官方的动画，计算过程有些问题…………我们看上去动画结束的时候，其实动画还在运行，一直在尝试将最后滑动距离跟终点目标值的距离降低至double的双精度允许损失范围内；但是这个左右摇摆的幅度特别小，我们看不出来……但毕竟还是一直计算没有结束动画的；

通俗的话来说，就是这个动画，一直在终点那块左右摇摆，直到达到终点；用个PageView，各个Item颜色区别设置大点，用大力一划这个左右摇摆的效果就能看的非常明显；

回正题，如果要想达到官方ListVIew的效果，取消掉动画过程中对手势的拦截即可，但是我还没试过这样会不会导致计算异常之类的问题……讲道理应该不会吧……这块手势操作的响应效果还是有点复杂的，我也不是很确定～～～

不过我个人感觉吧，解决这个问题应该在动画结束判断这块做下处理；比如说：1、更好的计算方式，让它一次性就到终点，别在那为了计算那一丢丢的范围而耗时；2、将允许的精度损失范围调大，让动画没必要停的那么精准，反正一般人也看不出来；3、让动画运行的更快点，可以通过减少动画的耗时，以及上面提到的，增加动画的速度来让动画更早结束（其实很多小说阅读器都没允许那种大力出奇迹的翻页方式，都是一页页翻页的，所以其实把那个动画耗时降低点问题就不大）；

**Comment by flymzero** [comment]
谢谢详细解答，我先去学习学习你的代码，感谢

**Comment by GoodReese** [comment]
> 额，是，因为我就这么规定的……在动画结束前不响应任何手势操作……看像小米阅读那个也是这样……
> 
> 不过Flutter的动画结束判断目测比原生上慢个0.3秒左右，而且确实我为了方便开发，动画设置的相对较慢，所以现在这个问题确实比较明显；
> 
> 临时性质的方案：
> 
> [fluttercandies/extended_image#152 (comment)](https://github.com/fluttercandies/extended_image/issues/152#issue-579677792)
> 
> 当然，个人感觉，接着重写，把Android 的那套搬过来才是正途～

用了这个方案后，动画有时候翻到一半就会变得很慢，不知道是不是我改错地方了，请大佬指教
<img width="570" alt="image" src="https://user-images.githubusercontent.com/93602754/166256843-cc2d245c-102d-439f-8984-f85bc21b1fea.png">
