### ISSUE TITLE
我不想自己编译

### ISSUE THREAD

**Issue by suihs11** [lwlizhe/flutter_novel#2]
对于 README.md 里面第一句话 "如果你想自己编译"...
我想说，我不想自己编译，但是我没看到项目里有可以安装的软件包，
项目 releases 也是空的！

**Comment by lwlizhe** [comment]
战术挠头……
额，讲真的，编译一下很快的，那句话的主要目的是提醒编译版本不要低于那个要求……

**Comment by lwlizhe** [comment]
补充上了android的安装包：
https://github.com/lwlizhe/flutter_novel/tree/master/demo/android

**Comment by suihs11** [comment]
主要是我本地 flutter 快一年没用了，都快忘了怎么用了

**Comment by lwlizhe** [comment]
总之，我上传了那个Android 的包，ios的包这个，我没开发环境，就爱莫能助了……

**Comment by suihs11** [comment]
我也没 ios 手机，要的就是安卓包
