### ISSUE TITLE
新版的仿真和原来Custompaint的仿真翻页，性能差距大吗

### ISSUE THREAD

**Issue by Passer-by** [lwlizhe/flutter_novel#20]
似乎Custompaint会来的更加流畅一点，我已经通过修改PageScrollPhysics 来让动画更快结束。
而且在快速滑动的时候，似乎会出现一些奇怪的现象。  比如说 从第四章直接跳到第一章了

**Comment by lwlizhe** [comment]
单纯只指翻页动画这块的页面性能的话，其实应该差不多，虽然新版的仿真加了好几个图层，额外的图层合并操作是给Raster带来了额外的压力，但是之前的仿真绘制还是用的将整个页面转为Image或者Picture的方式，这会给UI线程带来压力，所以吧，这两者其实都会造成性能影响；

我用这个新版的翻页动画，其实是想利用现有的Text等控件，实现诸如图文混排、动画、点击长按等手势交互等flutter自带的功能，原有的canvas毕竟只能绘制，要做更多功能就不太够了；而且能利用ListView自带的缓存功能来做个章节管理功能之类的，省事不少；也能做页面管理，结合状态管理框架方便实现章节跳转等功能；

回正题，如果你觉得CustomPaint的方式比较快的，我感觉，可能是我写的有点问题……也有可能是动画速度不够快，体现出卡卡的感觉……总之我个人测试了一下，其实好像没啥太大差别，甚至好像新版的仿真更快点……所以最好能提供一下最小测试单元或者demo，如果能提供性能对比就更好了，我看下具体哪里的问题；

至于后面这个快速滑动从第四章跳到第一章的问题…………没啥头绪…………可能是因为还没去处理快速滑动的问题，所以并没遇到过…………我只能大体盲猜一下，你的管理章节的ListView可能是一个只有3个的无限循环ListView，然后快速滑动的时候没做好手势的处理，导致本来应该是页面的ListView负责处理手势的部分，传递给了外层的负责章节的ListView，导致是章节ListView翻页而非章节内部的页面ListView翻页，可能是这样的异常导致了章节管理模块出现错误，进而使那个循环ListView没有更新下一章的内容…………

纯属盲猜哈，最好附一下最小测试单元或者demo项目

**Comment by Passer-by** [comment]
我用的是dev_2.0 那个分支进行测试的，我个人感觉问题可能也是在手势管理那一块。等空了在研究研究

**Comment by Passer-by** [comment]
> 

抱歉。是我改了一个地方导致的。原来的demo是没问题的 。
