### ISSUE TITLE
重构的代码里 单击翻页准备怎么实现。

### ISSUE THREAD

**Issue by Passer-by** [lwlizhe/flutter_novel#21]

**Comment by lwlizhe** [comment]
ListView嘛，通过调用ScrollController跳转；

再不行拿到ListView的PagePosition，调用position.animateTo ；

再不行逼急眼了直接用GestureBinding.dispatchEvent 模拟一个滑动手势过去……

**Comment by a1017480401** [comment]
> 



> ListView嘛，通过调用ScrollController跳转；
> 
> 再不行拿到ListView的PagePosition，调用position.animateTo ；
> 
> 再不行逼急眼了直接用GestureBinding.dispatchEvent 模拟一个滑动手势过去……
emmmm
两个listview呢 获取GestureBinding.dispatchEvent是最好用的？

**Comment by Passer-by** [comment]
> ListView嘛，通过调用ScrollController跳转；
> 
> 再不行拿到ListView的PagePosition，调用position.animateTo ；
> 
> 再不行逼急眼了直接用GestureBinding.dispatchEvent 模拟一个滑动手势过去……

两个listview呢，或许GestureBinding.dispatchEvent 是最优解。但我想在事件分发里面直接处理

**Comment by Passer-by** [comment]
啊。可以把父的Controller给子 。让子去做判断。唉。我太傻了

**Comment by Passer-by** [comment]
但我总感觉这样不太优雅。

**Comment by lwlizhe** [comment]
现在仔细想想，好像这东西可以内置一下……跟那个NestedScrollView一样，说白了就是搞个自定义的ScrollController，初始化的时候提供一个ScrollController强行设置给子List；不过应该仅限翻页这种原子化的操作，要么不做，要做就做完的那种，复杂操作的话，要考虑的东西太多……

**Comment by Passer-by** [comment]
对，算了，我还是直接全部交给子view处理把。这个可以等后面再优化

**Comment by Passer-by** [comment]
dev_2.0 分支里默认继承的是pageController  如果要改，改动量还挺大的

**Comment by lwlizhe** [comment]
我想想，要是改的话，可以这样？

直接像PrimaryScrollController那样，搞个InheridWidget，在子ListView的build方法中，获取这个InheridWidget，就能实现父子ScrollController的交互了倒是；

然后每次调用nextPage方法的时候，先判断子List的Controller列表中，对应父PageController的page的那个controller是否已经到了边界是否可以接着滑动，没到边界，就由那个子ListView的controller去处理nextPage，否则就是父ListVIew的Controller去处理

这样好像可以省事很多？

**Comment by Passer-by** [comment]
emmm实现的方法可能有很多种。但总感觉不太优雅。不过还是感谢你的解答 ，等我把其他功能完善了，再具体来处理这个事情吧。（先保证能用

**Comment by Passer-by** [comment]
关于这个问题。我个人认为单个listview可能会好点？（不确定 ） 因为两个listview的话，会最多build7个界面  前一章（倒一倒二）
中间那章（前中后） 最后那章的（第一第二）  当然也可以设置不缓存。但是这样快速滑动的时候 如果页面复杂，会不会导致加载慢了点（我没试过，个人猜测

**Comment by lwlizhe** [comment]
实在不行调整一下ListVIew的cacheExtent就行了，设置大点就多预加载点

**Comment by lwlizhe** [comment]
主要是用单个ListView的话，章节管理就要自己搞……
