### ISSUE TITLE
如果用户是从第100章开始阅读的话，要怎么做。。

### ISSUE THREAD

**Issue by Passer-by** [lwlizhe/flutter_novel#23]
前面的章节要如何处理。listview要双向加载了

**Comment by lwlizhe** [comment]
如果是跳转到100章的话，我的想法是直接修改那个，包裹章节ListView的那个最顶层ListView，设置其index为100，然后里面的章节ListView自动会去预加载99和101的内容；

然后章节ListView会根据分配的index去请求内容，请求到内容最后解析的时候，根据用户当前浏览的章节index，判断出当前加载的是前一章、后一章还是当前章；前一章的话，把pageIndex设置为最后一页就行了

**Comment by Passer-by** [comment]
> 如果是跳转到100章的话，我的想法是直接修改那个，包裹章节ListView的那个最顶层ListView，设置其index为100，然后里面的章节ListView自动会去预加载99和101的内容；
> 
> 然后章节ListView会根据分配的index去请求内容，请求到内容最后解析的时候，根据用户当前浏览的章节index，判断出当前加载的是前一章、后一章还是当前章；前一章的话，把pageIndex设置为最后一页就行了

这样在滑动的时候会疯狂build的。。

**Comment by lwlizhe** [comment]
> > 如果是跳转到100章的话，我的想法是直接修改那个，包裹章节ListView的那个最顶层ListView，设置其index为100，然后里面的章节ListView自动会去预加载99和101的内容；
> > 然后章节ListView会根据分配的index去请求内容，请求到内容最后解析的时候，根据用户当前浏览的章节index，判断出当前加载的是前一章、后一章还是当前章；前一章的话，把pageIndex设置为最后一页就行了
> 
> 这样在滑动的时候会疯狂build的。。

如果滑动的范围是一章内的话，倒是不会有啥影响，因为对于最外层的ListView来说，item范围没改变，也不会触发build；

唯一可能有影响的地方是章节切换这块，但是也仅仅build下一章或者上一章一次，再滑动的就由对应章节ListVIew来接管事件了，如果在model层面做了缓存处理，那其实build影响不大，毕竟现在解析一章内容（3000字）的时间仅仅是1ms左右，几乎无影响；

**Comment by a1017480401** [comment]
> 



> > > 如果是跳转到100章的话，我的想法是直接修改那个，包裹章节ListView的那个最顶层ListView，设置其index为100，然后里面的章节ListView自动会去预加载99和101的内容；
> > > 然后章节ListView会根据分配的index去请求内容，请求到内容最后解析的时候，根据用户当前浏览的章节index，判断出当前加载的是前一章、后一章还是当前章；前一章的话，把pageIndex设置为最后一页就行了
> > 
> > 
> > 这样在滑动的时候会疯狂build的。。
> 
> 如果滑动的范围是一章内的话，倒是不会有啥影响，因为对于最外层的ListView来说，item范围没改变，也不会触发build；
> 
> 唯一可能有影响的地方是章节切换这块，但是也仅仅build下一章或者上一章一次，再滑动的就由对应章节ListVIew来接管事件了，如果在model层面做了缓存处理，那其实build影响不大，毕竟现在解析一章内容（3000字）的时间仅仅是1ms左右，几乎无影响；

**Comment by Passer-by** [comment]
> > > 如果是跳转到100章的话，我的想法是直接修改那个，包裹章节ListView的那个最顶层ListView，设置其index为100，然后里面的章节ListView自动会去预加载99和101的内容；
> > > 然后章节ListView会根据分配的index去请求内容，请求到内容最后解析的时候，根据用户当前浏览的章节index，判断出当前加载的是前一章、后一章还是当前章；前一章的话，把pageIndex设置为最后一页就行了
> > 
> > 
> > 这样在滑动的时候会疯狂build的。。
> 
> 如果滑动的范围是一章内的话，倒是不会有啥影响，因为对于最外层的ListView来说，item范围没改变，也不会触发build；
> 
> 唯一可能有影响的地方是章节切换这块，但是也仅仅build下一章或者上一章一次，再滑动的就由对应章节ListVIew来接管事件了，如果在model层面做了缓存处理，那其实build影响不大，毕竟现在解析一章内容（3000字）的时间仅仅是1ms左右，几乎无影响；

还需要考虑一些业务上的变化，如果说每个页面都有一个值。值是实时刷新的。

**Comment by lwlizhe** [comment]
额，我感觉其实如果页面上有变化的值，好像也不会影响到最外层的ListView导致其build，其实有点不太明白现在说的是啥场景会导致啥问题……你的意思是比如说加个时钟或者电量么？

**Comment by Passer-by** [comment]
> 额，我感觉其实如果页面上有变化的值，好像也不会影响到最外层的ListView导致其build，其实有点不太明白现在说的是啥场景会导致啥问题……你的意思是比如说加个时钟或者电量么？

对。就是电量和时钟

**Comment by lwlizhe** [comment]
这个话感觉这种放到page内容中，不参与章节的东西，其实影响不大；build的话用局部刷新，不会触发外层的ListView build吧，一般这些东西都是固定大小、固定范围和位置的；paint的话倒可能确实存在些问题，因为仿真翻页这种不能用repaintBoundary……但是应该也没到那种手势操作级别的绘制频率，我感觉问题也不大
