### ISSUE TITLE
仿真翻页不跟手

### ISSUE THREAD

**Issue by GoodReese** [lwlizhe/flutter_novel#24]
感谢大佬的库，很不错！

不过仿真翻页这块不太跟手，请问该怎么优化呢？
纵观全网，只有你这边有flutter版本的仿真翻页啦～

**Comment by lwlizhe** [comment]
造成这个的原因是因为我将ListView设置为在完成动画之前不接受任何手势操作，所以在一次翻页动画完成前快速滑动再次翻页是没有效果的

当然，如果直接把动画改快点，应该会好很多，现在我为了方便调试和看效果，好像设置的是200ms还是500ms来着（最近在忙好多事，一段时间没看代码了）……或者改进下flutter的动画机制，让他动画结束判断的阈值没必要精确到小数点那么多（因为flutter中结束动画的判断依据是根据到目标位置的差值是否小于一个阈值，而这个阈值的小数点位好像很多），根据实测，后面有一段时间一直在跟小数点作斗争，但这实际上肉眼是看不出来的；

如果有能力，可以直接去做不拦截手势的方案，这应该是最优解；不过这样的话，要考虑的东西就挺多了，各种状态下对于手势的处理，以及状态的中断、回复之类的

**Comment by lwlizhe** [comment]
对了，接下来我计划对翻页动画这块进行下改进，用离屏缓存的方式缓存一下最后构建的页面，canvas改为使用image而非drawChild，这样会去掉诸如不能使用repaintBoundary之类的限制，不过这可能会造成现有代码的大范围改动，不过能确保的是基本思路不变，所以目前的方式仅供参考学习哈；

**Comment by CaiJiangYang1** [comment]
> 

大佬你好，这个小数点斗争应该在哪里改呢？
动画的时间我改到300ms，有好一些
但是不懂如何改进flutter的动画机制
可以麻烦辛苦指出在哪里修改吗？谢谢您

另外，很期待您的翻页动画更新，希望能出一个插件，不要耦合太高，全网唯一！

**Comment by zhangyyysss** [comment]
大佬很棒~

**Comment by GoodReese** [comment]
转眼2年,看来这个项目已经G了

**Comment by lwlizhe** [comment]
> 转眼2年,看来这个项目已经G了

如果我红着脸梗着脖子，假装有底气的说，在搞了在搞了，这回有新方案的！用FragmentShader实现的[方案](https://juejin.cn/post/7337941065020801065)，性能非常高，fps>=50，都能有95%以上，更别提什么卡顿了

**Comment by GoodReese** [comment]
> > 转眼2年,看来这个项目已经G了
> 
> 如果我红着脸梗着脖子，假装有底气的说，在搞了在搞了，这回有新方案的！用FragmentShader实现的[方案](https://juejin.cn/post/7337941065020801065)，性能非常高，fps>=50，都能有95%以上，更别提什么卡顿了

哈哈哈 22号发布的 挺巧啊

**Comment by lwlizhe** [comment]
> > > 转眼2年,看来这个项目已经G了
> > 
> > 
> > 如果我红着脸梗着脖子，假装有底气的说，在搞了在搞了，这回有新方案的！用FragmentShader实现的[方案](https://juejin.cn/post/7337941065020801065)，性能非常高，fps>=50，都能有95%以上，更别提什么卡顿了
> 
> 哈哈哈 22号发布的 挺巧啊

这回的新技术方案还是挺让人振奋的，我现在已经完成了glsl的翻页动画，剩下的就是应用上去，前面提到的那个动画速率和时长限制问题目前也找到了方案，如果你还信任我的话🐶🐶🐶，这回出的成果应该很不错的。

**Comment by GoodReese** [comment]
> > > > 转眼2年,看来这个项目已经G了
> > > 
> > > 
> > > 如果我红着脸梗着脖子，假装有底气的说，在搞了在搞了，这回有新方案的！用FragmentShader实现的[方案](https://juejin.cn/post/7337941065020801065)，性能非常高，fps>=50，都能有95%以上，更别提什么卡顿了
> > 
> > 
> > 哈哈哈 22号发布的 挺巧啊
> 
> 这回的新技术方案还是挺让人振奋的，我现在已经完成了glsl的翻页动画，剩下的就是应用上去，前面提到的那个动画速率和时长限制问题目前也找到了方案，如果你还信任我的话🐶🐶🐶，这回出的成果应该很不错的。

全网可是你就你这有flutter仿真翻页,虽然我现在用不上这个库,但还是支持你,收藏了~
