### ISSUE TITLE
大佬您好，来挖人了，万一挖动了呢

### ISSUE THREAD

**Issue by stone-smilenovel** [lwlizhe/flutter_novel#25]
您好，我们是一家面向中东的小说阅读平台，您的代码对我们启发很大，所以想尝试过来挖一挖，业务方面处在上升期，机会还是蛮多的，不知道您有没有兴趣深入聊一下，我的微信：stone2506

**Comment by lwlizhe** [comment]
额，不好意思，最近正巧刚刚换工作，目前也没遇到什么不满意的地方，所以暂时没有什么跳槽的计划；不过大家可以加一下方便沟通
