### ISSUE TITLE
作者大大您好，请问可以给个联系方式吗？想了解一下Provider的部分，有点没看懂

### ISSUE THREAD

**Issue by AHRL** [lwlizhe/flutter_novel#3]
作者大大您好，请问可以给个联系方式吗？想了解一下Provider的部分，有点没看懂

**Comment by lwlizhe** [comment]
Provider这块框架是用一个国外大佬的框架，我感觉蛮不错的

顺便附上他的课程demo：
https://github.com/FilledStacks/flutter-tutorials

记得是第14天的v3版本，你可以看下它的讲解视频以及之前关于provider的视频，感觉都说的蛮好的

**Comment by AHRL** [comment]
好的，谢谢~
