### ISSUE TITLE
provider的问题

### ISSUE THREAD

**Issue by AHRL** [lwlizhe/flutter_novel#4]
在书架部分：
`
NovelBookShelfViewModel buildViewModel(BuildContext context) {
    return NovelBookShelfViewModel(
      Provider.of(context),
      Provider.of(context),
    );
  }
`
这里的两个Provider.of(context)能解释一下吗？谢谢~

**Comment by lwlizhe** [comment]
provider.of不是返回一个泛型嘛，所以你看下构造NovelBookShelfViewModel到底需要的是什么东西；

我这里NovelBookShelfViewModel的构造器中需要的是NovelBookDBModel和NovelBookNetModel，而这两个是通过刚开始传入的，具体可以在那个provider_setup.dart中查看；

所以结构是这样的：
全局所有需要的model，放在最顶层；全局需要的功能性model，通过ProxyProvider获取所需的功能模块构造出来并放在最顶层；这样做的目的就是，其他任何并不是全局需要的viewModel，就可以通过Provider.of(context)获取所需model，并直接在对应的子页面中单独构造，而不是全部放在最顶层搞得很乱

**Comment by AHRL** [comment]
我明白了，谢谢~
