### ISSUE TITLE
大佬好，我的后台阅读数据是这样返回，数据替换要如何修改，不太会改

### ISSUE THREAD

**Issue by wozhizhizhi** [lwlizhe/flutter_novel#5]
这是后台返回阅读数据   
{
    "code": 10000,
    "data": {
   "current": {   //当前阅读章节
          "id": "235499",
          "bid": "11631",
          "coin": "0",
          "num": 2,
          "name": "第三章  彪悍的叶辰",
          "is_buy":0    //未后买章节
          "link": "https://cdn./front/chapter_info/11631_2_11bacdfc1b2ce4a14fec64c49e1bb0ea.js"
    },
    "book": {      //书籍基本详情
        "id": "11631",
        "name": "武动神尊",
        "status": "1",
        "auto_buy": "1"    //自动续费
        "spic": "updata/book/201904/201904121626098346.jpeg"
    },
        "prev": {      //前一章节
            "num": 1,
            "link": "https://11631_1_11bacdfc1b2ce4a14fec64c49e1bb0ea.js"
        },
        "next": {      //后一章节
            "num": 3,
            "link": "https:///11631_3_11bacdfc1b2ce4a14fec64c49e1bb0ea.js"
        },
        "auto_buy": true,         //是否自动续费
        "shelf_status": fales, //是否以在书架
        "ad_chapter": "",      //底部广告
        "recommend_info": ""   //推荐书籍
        "coin_currency": "9941",//当前书币
        "coin_arch": "20"，     //当前书券
    }
  }

**Comment by lwlizhe** [comment]
依稀记得需要传入一个章节内容，以及实现一个获取小说内容的接口就行了

记得是setChapter和onRequestContent这俩吧，名字差也差不了多少

总之这块具体实现还是要看你们业务……你这丢给我一个这个后台返回数据……我也不太懂你们的逻辑，只能说下我目前的实现方式

**Comment by wozhizhizhi** [comment]
好的谢谢大佬我我找一下，后台根据页数和书ID一次返回当前章节，上一章节和下一章，每次请求都会返回这3块数据，每次切换都是拿对应章节的页数去请求这个接口

**Comment by lwlizhe** [comment]
那可能跟我这的实现方式有冲突，主要是我这是先要传入一个完证的目录的……

我这阅读器模块是自己维护章节指针什么的，那些上一章下一章，章节跳转什么的都是从这个完整目录中过去需要信息，然后请求接口来获取具体的章节内容

**Comment by wozhizhizhi** [comment]
好的谢谢大佬，上面说的提醒我了，我这边可以获取到完整目录
