### ISSUE TITLE
大佬我来求教了，请问文章的内容展示区域如何调整

### ISSUE THREAD

**Issue by wozhizhizhi** [lwlizhe/flutter_novel#6]
非常感谢大佬上次的指点，翻书的效果已经集成进去了，目前我又遇到的了一个问题看了大佬2天的源码能力有限还是不知道怎么调整控制文字显示区域增加一些控件上去，没办法了只有来打搅大佬的了，现在要求有些章节是需要付费才能看到，没有付费只展示一下段文字，文字下面是自动付费和购买的布局，后台是一次性把文章内容都返回回来，还是没想好这块怎么动才好，求大佬赐教

**Comment by lwlizhe** [comment]
额，目前我这阅读页是直接用canvas绘制文字上去的……

或许，你在实现那个获取章节内容页的时候可以做个判断

如果是正常阅读内容，那么用我做的这个阅读页；
如果是那种需要付费的，或者别的什么错误页，通过状态管理这种东西，加载一个自定义的错误页，隐藏掉我那个阅读页

**Comment by wozhizhizhi** [comment]
好的非常谢谢大佬提示，我这样试一试
