### ISSUE TITLE
膜拜大佬，大佬人也很好，看了iss，每个都耐心的回复。国人真好

### ISSUE THREAD

**Issue by ngxu** [lwlizhe/flutter_novel#7]
已star，我是做RN的，前来学习。感谢大佬！

**Comment by ngxu** [comment]
我想问个问题，该项目的仿真翻页是集成的原生还是flutter的～～  期待大佬回复

**Comment by lwlizhe** [comment]
大佬这个就过奖了~~交流学习而已

这个项目全都是flutter的
